Repository wireapp/rusty-jwt-tools, pull requests merged in 2024-02, with the labels that each got.

#154 fix: Rework x509 verification to be sturdier
  Cargo.lock
  x509-check/src/revocation.rs
Labels: bug, enhancement

#156 feat: add serial number, not before & not after in the identity object
  acme/Cargo.toml
  acme/src/identity/mod.rs
Labels: enhancement

#160 fix: Use vendored OpenSSL for testing
  Cargo.lock
  e2e-identity/Cargo.toml
Labels: dependencies
